<?php

/**
 * @author abdellah.latreche04@gmail.com | Mini LMS | 2026
 *
 * Formation authorization.
 *
 * - Admin: full access on every formation.
 * - Student: may view a formation if it is published AND they are enrolled.
 *            May update/delete a formation only if they are its creator
 *            (i.e. the formation was AI-generated by them).
 */

namespace App\Policies;

use App\Models\Formation;
use App\Models\User;

class FormationPolicy
{
    public function viewAny(User $user): bool
    {
        return true;
    }

    public function view(User $user, Formation $formation): bool
    {
        if ($user->isAdmin()) {
            return true;
        }

        if ($formation->isOwnedBy($user)) {
            return true;
        }

        return $formation->status === 'published'
            && $formation->students()->where('user_id', $user->id)->exists();
    }

    public function create(User $user): bool
    {
        return $user->isAdmin() || $user->isStudent();
    }

    public function update(User $user, Formation $formation): bool
    {
        return $user->isAdmin() || $formation->isOwnedBy($user);
    }

    public function delete(User $user, Formation $formation): bool
    {
        return $user->isAdmin() || $formation->isOwnedBy($user);
    }
}
