<?php

/**
 * @author abdellah.latreche04@gmail.com | Mini LMS | 2026
 *
 * Model representing an AI-generated content entry.
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;

class AiGeneration extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'user_id',
        'prompt',
        'generated_content',
        'type',
        'status',
        'validated_at',
    ];

    protected function casts(): array
    {
        return [
            'validated_at' => 'datetime',
        ];
    }

    // Relationships

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    // Status Helpers

    public function isDraft(): bool
    {
        return $this->status === 'draft';
    }

    public function isPublished(): bool
    {
        return $this->status === 'published';
    }

    public function isValidated(): bool
    {
        return $this->status === 'validated';
    }

    /**
     * Content is editable only while in draft status.
     */
    public function isEditable(): bool
    {
        return $this->isDraft();
    }

    /**
     * Check if a user owns this generation.
     */
    public function isOwnedBy(User $user): bool
    {
        return $this->user_id === $user->id;
    }

    /**
     * Check if this was generated by an admin.
     */
    public function isAdminContent(): bool
    {
        return $this->user?->isAdmin() ?? false;
    }

    /**
     * Check if this was generated by a student.
     */
    public function isStudentContent(): bool
    {
        return $this->user?->isStudent() ?? false;
    }

    // Scopes

    public function scopeByUser($query, int $userId)
    {
        return $query->where('user_id', $userId);
    }

    public function scopeDraft($query)
    {
        return $query->where('status', 'draft');
    }

    public function scopePublished($query)
    {
        return $query->where('status', 'published');
    }

    public function scopeValidated($query)
    {
        return $query->where('status', 'validated');
    }

    public function scopeStudentOwned($query)
    {
        return $query->whereHas('user', fn($q) => $q->where('role', 'apprenant'));
    }

    public function scopeAdminOwned($query)
    {
        return $query->whereHas('user', fn($q) => $q->where('role', 'admin'));
    }

    // Status Badge

    public function getStatusLabelAttribute(): string
    {
        return match ($this->status) {
            'draft' => 'Brouillon',
            'published' => 'Publié',
            'validated' => 'Validé',
            default => $this->status,
        };
    }

    public function getStatusColorAttribute(): string
    {
        return match ($this->status) {
            'draft' => 'slate',
            'published' => 'emerald',
            'validated' => 'sky',
            default => 'slate',
        };
    }
}
